VendorMgmt.Web/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Caching;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Caching;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.UI;
using VendorMgmt.DataAccess;
using VendorMgmt.DataAccess.Model;
using VendorMgmt.Helper;
using CacheItemPriority = System.Web.Caching.CacheItemPriority;

namespace VendorMgmt.Web.Controllers
{

    public class VendorController : Controller
    {
        public VendorService vs = new VendorService();
        public VendorService Customervs = new VendorService("s");
        // GET: Vendor
        public ActionResult FillInfo(VendorFillInfo model, string LinkGuid = "")
        {
            if (LinkGuid == string.Empty)
            {
                TempData["Error"] = "No Registration Code Provided";
            }
            else
            {

                var VendorMst = vs.VendorMasters.Where(p => p.LinkGuid == LinkGuid && p.LinkExpired == false).FirstOrDefault();
                if (VendorMst == null)
                {
                    TempData["Error"] = "Invalid Registration Code or Registration Code Expired";
                    return View(model);
                }

                model.RegistrationCode = VendorMst.RegistrationCode;
                model.BusinessName = VendorMst.BusinessName;
                model.VendorEmail = VendorMst.VendorEmail;
                model.DofascoEmail = VendorMst.DofascoEmail;
                model.LinkGuid = LinkGuid;
                var Basicinfo = Customervs.VendorBasicInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.BasicInfo = Basicinfo == null ? new VendorBasicInfo() : Basicinfo;

                var FinancialInfo = Customervs.VendorFinancialInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.FinancialInfo = FinancialInfo == null ? new VendorFinancialInfo() : FinancialInfo;

                var PrimarySalesInfo = Customervs.VendorPrimarySalesInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.PrimarySalesInfo = PrimarySalesInfo == null ? new VendorPrimarySalesInfo() : PrimarySalesInfo;

                var SubmittedByInfo = Customervs.VendorSubmittedByInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.SubmittedByInfo = SubmittedByInfo == null ? new VendorSubmittedByInfo() : SubmittedByInfo;

                var RemittanceInfo = Customervs.VendorRemittanceInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.RemittanceInfo = RemittanceInfo == null ? new VendorRemittanceInfo() : RemittanceInfo;

                var BankingInfo = Customervs.VendorBankingInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.BankingInfo = BankingInfo == null ? new VendorBankingInfo() : BankingInfo;

                List<VendorAttachmentInfo> LstAttachment = Customervs.VendorAttachmentInfos.Where(p => p.VendorId == VendorMst.Id).ToList();
                model.AttachmentInfo = LstAttachment;

                var PurchaseInfo = Customervs.VendorPurchasingInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.PurchaseInfo = PurchaseInfo == null ? new VendorPurchasingInfo() : PurchaseInfo;

                var WorkFlowInfo = Customervs.VendorWorkFlowInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.WorkFlowInfo = WorkFlowInfo == null ? new VendorWorkFlowInfo() : WorkFlowInfo;

                var TreasuryInfo = Customervs.VendorTreasuryInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.TreasuryInfo = TreasuryInfo == null ? new VendorTreasuryInfo() : TreasuryInfo;

                model.VendorId = VendorMst.Id;

                ViewData["SpanTreeLevel1"] = new SelectList(Customervs.SpanTreeLevels.Where(p => p.LevelId == 1).ToList(), "LevelCode", "LevelDescription");
                vs.SetLinkExpired(VendorMst.Id);
                Customervs.VendorMasterCustomer_InsertOrUpdate(VendorMst);
            }
            return View(model);
        }
        [HttpPost]
        public JsonResult ValidateForm(VendorFillInfo model)
        {
            var VendorMst = vs.VendorMasters.Where(p => p.RegistrationCode == model.RegistrationCode).FirstOrDefault();

            if (model.UserRegistrationCode == VendorMst.RegistrationCode && model.Email.ToLower() == VendorMst.VendorEmail.ToLower() && model.CompanyName.ToLower() == VendorMst.BusinessName.ToLower())
            {
                return Json(new { data = "Success" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { data = "Authentication Failed" }, JsonRequestBehavior.AllowGet);
            }
        }
        public async Task<ActionResult> GetDetails(string RegistrationCode)
        {
            if (Request.Cookies["UserToken"] != null)
            {
                //You get the user's first and last name below:
                ViewBag.Name = Request.Cookies["UserName"]?.Value;
                ViewBag.UserGuid = Request.Cookies["UserGuid"]?.Value;
                // The 'preferred_username' claim can be used for showing the username
                ViewBag.Username = Request.Cookies["UserEmail"]?.Value;
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            VendorFillInfo model = new VendorFillInfo();
            if (RegistrationCode == string.Empty)
            {
                TempData["Error"] = "No Registration Code Provided";
            }
            else
            {
                model.RegistrationCode = RegistrationCode;
                var VendorMst = vs.VendorMasters.Where(p => p.RegistrationCode == RegistrationCode).FirstOrDefault();
                if (VendorMst == null)
                {
                    TempData["Error"] = "Invalid Registration Code or Registration Code Expired";
                    return PartialView(model);
                }
                model.BusinessName = VendorMst.BusinessName;
                model.VendorEmail = VendorMst.VendorEmail;
                model.DofascoEmail = VendorMst.DofascoEmail;
                model.IsPurchaseManagerApproved = VendorMst.PurchaseManagerApproved;
                model.IsWorldCheckApproved = VendorMst.WorldCheckApproved;
                model.IsTreasuryValidated = VendorMst.TreasuryValidated;
                var Basicinfo = vs.VendorBasicInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.BasicInfo = Basicinfo == null ? new VendorBasicInfo() : Basicinfo;

                var FinancialInfo = vs.VendorFinancialInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.FinancialInfo = FinancialInfo == null ? new VendorFinancialInfo() : FinancialInfo;

                var PrimarySalesInfo = vs.VendorPrimarySalesInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.PrimarySalesInfo = PrimarySalesInfo == null ? new VendorPrimarySalesInfo() : PrimarySalesInfo;

                var SubmittedByInfo = vs.VendorSubmittedByInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.SubmittedByInfo = SubmittedByInfo == null ? new VendorSubmittedByInfo() : SubmittedByInfo;

                var RemittanceInfo = vs.VendorRemittanceInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.RemittanceInfo = RemittanceInfo == null ? new VendorRemittanceInfo() : RemittanceInfo;

                var BankingInfo = vs.VendorBankingInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.BankingInfo = BankingInfo == null ? new VendorBankingInfo() : BankingInfo;

                List<VendorAttachmentInfo> LstAttachment = vs.VendorAttachmentInfos.Where(p => p.VendorId == VendorMst.Id).ToList();
                model.AttachmentInfo = LstAttachment;

                var PurchaseInfo = vs.VendorPurchasingInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.PurchaseInfo = PurchaseInfo == null ? new VendorPurchasingInfo() : PurchaseInfo;

                var WorkFlowInfo = vs.VendorWorkFlowInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.WorkFlowInfo = WorkFlowInfo == null ? new VendorWorkFlowInfo() : WorkFlowInfo;

                var TreasuryInfo = vs.VendorTreasuryInfos.Where(p => p.VendorId == VendorMst.Id).FirstOrDefault();
                model.TreasuryInfo = TreasuryInfo == null ? new VendorTreasuryInfo() : TreasuryInfo;

                model.VendorId = VendorMst.Id;
                if (System.Web.HttpContext.Current.Cache["lstAzureUsers"] == null)
                {
                    model.lstUsers = await MicrosoftGraphClient.GetAllUsers();
                    System.Web.HttpContext.Current.Cache.Add("lstAzureUsers", model.lstUsers, null, DateTime.Now.AddMinutes(120), Cache.NoSlidingExpiration, CacheItemPriority.AboveNormal, null);
                }
                else
                {
                    model.lstUsers = System.Web.HttpContext.Current.Cache["lstAzureUsers"] as List<AzureUserList>;
                }
                ViewData["SpanTreeLevel1"] = new SelectList(vs.SpanTreeLevels.Where(p => p.LevelId == 1).ToList(), "LevelCode", "LevelDescription", model.PurchaseInfo != null ? model.PurchaseInfo.SpendTreelevel1 : "#");
                if (model.PurchaseInfo != null)
                {
                    ViewData["SpanTreeLevel2"] = new SelectList(vs.SpanTreeLevels.Where(p => p.LevelId == 2 && p.ParentLevelText == model.PurchaseInfo.SpendTreelevel1).ToList(), "LevelCode", "LevelDescription", model.PurchaseInfo != null ? model.PurchaseInfo.SpendTreeLevel2 : "");

VendorMgmt.Web/Views/Vendor/PurchaseApproverConfirmation.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Vendor Management</title>

    <!-- favicons -->
    <link rel="icon" type="image/png" href="~/Theme/images/favicon.png">
    <link rel="apple-touch-icon" href="~/Theme/images/apple-touch-icon.png">


    <link href="~/Theme/css/bootstrap.min.css" rel="stylesheet" />

    <link href="~/Theme/css/font-awesome.min.css" rel="stylesheet" />

    @*<link href="~/Theme/css/simplebar.min.css" rel="stylesheet" />*@
    @*=========================================================
        This Page Styles
        =========================================================*@
    @*morris chart
        <link rel="stylesheet" href="./assets/vendor/morris/css/morris.min.css">*@
    <!-- toastr -->
    <link href="~/Theme/css/jquery.toast.min.css" rel="stylesheet" />
    <!-- data table -->
    <link href="~/Theme/css/jquery.dataTables.min.css" rel="stylesheet" />
    <!-- summernote editor -->
    <link href="~/Theme/css/summernote-bs4.css" rel="stylesheet" />
    @*Main Styles*@
    <link href="~/Theme/css/main.css?v=1.0" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link href="~/Theme/css/sweetalert2.min.css" rel="stylesheet" />
    @*@Styles.Render("~/Theme/css")*@
    <style type="text/css">
        main .main-header .header-info {
            padding: 5px 30px;
        }

        main .content {
            margin-top: 15px;
            margin-left: 15px;
            margin-right: 15px;
        }

        header {
            width: 100% !important;
            background: #FF3700;
        }

        main {
            margin-left: 0px;
        }

        .header-right {
            color: #fff;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <header>
            <div class="header-left">
                <!-- navigation-toggle  -->
                <a href="" class="header-btn side-nav-toggle">
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
                <div class="header">
                    <div class="logo">

                        <img src="~/Theme/images/Companylogo.png" style="height:65px;margin-right:10px;margin-top:5px;" />

                    </div>
                </div>
                <!-- window full screen -->
                @*<a href="" id="fullScreen" class="header-btn hide-md"><i class="fa fa-expand"></i></a>*@


            </div>
        <div style="text-align: center; color: white !important; vertical-align: middle; margin-top: 1%;">
            <h3 style="color:white !important;">VENDOR MANAGEMENT</h3>
        </div>
            <div class="header-right">
               
            </div>
        </header><!-- header //. -->
        <main>
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <div class="panel-body" style="margin-top: 15%;">
                            @using (Html.BeginForm("Success", "Vendor", FormMethod.Post, new { @class = "form-horizontal form-bordered", onsubmit = "showLoader(this);" }))
                            {

                                <div class="panel-body">
                                    <div class="col-md-12" style="text-align:center;">
                                        <h1>Thank you for submitting your vendor information</h1>
                                    </div>
                                    <div class="col-md-12" style="text-align:center;">
                                        <h3>You will receive an email confirmation shortly.</h3>
                                    </div>
                                </div>
                                @*<footer class="panel-footer"></footer>*@
                            }
                        </div>
                    </section>


                </div>
            </div>
        </main>
    </div>
</body>
</html>
@section scripts{

}

VendorMgmt.Web/Views/Vendor/Success.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Vendor Management</title>

    <!-- favicons -->
    <link rel="icon" type="image/png" href="~/Theme/images/favicon.png">
    <link rel="apple-touch-icon" href="~/Theme/images/apple-touch-icon.png">


    <link href="~/Theme/css/bootstrap.min.css" rel="stylesheet" />

    <link href="~/Theme/css/font-awesome.min.css" rel="stylesheet" />

    @*<link href="~/Theme/css/simplebar.min.css" rel="stylesheet" />*@
    @*=========================================================
        This Page Styles
        =========================================================*@
    @*morris chart
        <link rel="stylesheet" href="./assets/vendor/morris/css/morris.min.css">*@
    <!-- toastr -->
    <link href="~/Theme/css/jquery.toast.min.css" rel="stylesheet" />
    <!-- data table -->
    <link href="~/Theme/css/jquery.dataTables.min.css" rel="stylesheet" />
    <!-- summernote editor -->
    <link href="~/Theme/css/summernote-bs4.css" rel="stylesheet" />
    @*Main Styles*@
    <link href="~/Theme/css/main.css?v=1.0" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
    <link href="~/Theme/css/sweetalert2.min.css" rel="stylesheet" />
    @*@Styles.Render("~/Theme/css")*@
    <style type="text/css">
        main .main-header .header-info {
            padding: 5px 30px;
        }

        main .content {
            margin-top: 15px;
            margin-left: 15px;
            margin-right: 15px;
        }

        header {
            width: 100% !important;
            background: #FF3700;
        }

        main {
            margin-left: 0px;
        }

        .header-right {
            color: #fff;
        }
        .success {
            color: #ffffff;
            font-size: 100px;
            line-height: 200px;
            margin-left: -15px;
        }
        .fail {
            color: #ffffff;
            font-size: 100px;
            line-height: 200px;
            margin-left: 3px;
            font-style: normal !important;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <header>
            <div class="header-left">
                <!-- navigation-toggle  -->
                <a href="" class="header-btn side-nav-toggle">
                    <span></span>
                    <span></span>
                    <span></span>
                </a>
                <div class="header">
                    <div class="logo">

                        <img src="~/Theme/images/Companylogo.png" style="height:65px;margin-right:10px;margin-top:5px;" />

                    </div>
                </div>
                <!-- window full screen -->
                @*<a href="" id="fullScreen" class="header-btn hide-md"><i class="fa fa-expand"></i></a>*@


            </div>
        <div style="text-align: center; color: white !important; vertical-align: middle; margin-top: 1%;">
            <h3 style="color:white !important;">VENDOR MANAGEMENT</h3>
        </div>
            <div class="header-right">
               
            </div>
        </header><!-- header //. -->
        <main>
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <div class="panel-body" style="margin-top: 15%;">
                            @using (Html.BeginForm("Success", "Vendor", FormMethod.Post, new { @class = "form-horizontal form-bordered", onsubmit = "showLoader(this);" }))
                            {

                                <div class="panel-body">
                                    <div class="col-md-12" style="text-align:center;">
                                        @if (ViewBag.ApprovedStatus ==null || ViewBag.ApprovedStatus == "Approved")
                                        {
                                            <div style="border-radius:200px; height:200px; width:200px; background: #ff3700; margin:0 auto;">
                                                <i class="success">✓</i>
                                            </div>
                                        }
                                        else
                                        {
                                            <div style="border-radius:200px; height:200px; width:200px; background: #ff3700; margin:0 auto;">
                                                <i class="fail">X</i>
                                            </div>
                                        }
                                    </div>
                                    <div class="col-md-12" style="text-align:center;">
                                        <h3>The Vendor Request has been <span style="font-weight:bold;">@ViewBag.ApprovedStatus</span></h3>
                                    </div>
                                </div>
                                @*<footer class="panel-footer"></footer>*@
                            }
                        </div>
                    </section>


                </div>
            </div>
        </main>
    </div>
</body>
</html>
@section scripts{

}

VendorMgmt.Web/Views/Vendor/TestFileUpload.cshtml
@model List<VendorMgmt.DataAccess.Model.VendorAttachmentInfo> 

<h3>Upload File(s)</h3>
<style>
    .red {
        color: red;
    }
</style>
<form id="uploader">
    <div class="row">
        <div class="col-sm-6">
            <input id="fileInput" type="file" multiple>
            <br />            <br />

            <table class="table" id="FilesList" style="visibility:hidden">
                <tr>
                    <th>
                        Attachment(s)
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
                @if (Model.Count > 0)
                {
                    foreach (var item in Model)
                    {
                        <tr id='@item.Id'>
                            <td>
                                @item.FileName
                            </td>
                            <td>
                                <a href='#' onclick="DeleteServerFile('@item.Id');"><span class='red'><i class="fs-20 fa fa-trash mr-10"></i></span></a>
                            </td>
                        </tr>
                    }

                }
            </table>
            <input type="button" id="btnupload" value="Upload" style="float:right" />

        </div>
    </div>
</form>
@Scripts.Render("~/bundles/CustomTheme")
<script>

    var formdata = new FormData(); //FormData object
    $(document).ready(function () {
        chkatchtbl();
        $("#fileInput").on("change", function () {
            var fileInput = document.getElementById('fileInput');
            //Iterating through each files selected in fileInput
            for (i = 0; i < fileInput.files.length; i++) {

                var sfilename = fileInput.files[i].name;
                let srandomid = Math.random().toString(36).substring(7);

                formdata.append(sfilename, fileInput.files[i]);

                var markup = "<tr id='" + srandomid + "'><td>" + sfilename + "</td><td><a href='#' onclick='DeleteFile(\"" + srandomid + "\",\"" + sfilename +
                    "\")'><span class='red'><i class=\"fs-20 fa fa-trash mr-10\"></i></span></a></td></tr>"; // Binding the file name
                $("#FilesList tbody").append(markup);

            }
            chkatchtbl();
            $('#fileInput').val('');
        });

        $("#btnupload").click(function () {
            formdata.append('uploadername', $('#txtuploader').val());
            $.ajax({
                url: '/Vendor/UploadFiles',
                type: "POST",
                contentType: false, // Not to set any content header
                processData: false, // Not to process data
                data: formdata,
                async: false,
                success: function (result) {
                    if (result != "") {
                        alert(result);
                    }
                },
                error: function (err) {
                    alert(err.statusText);
                }
            });
        });
    });
    function DeleteFile(Fileid, FileName) {
        formdata.delete(FileName)
        $("#" + Fileid).remove();
        chkatchtbl();
    }
    function chkatchtbl() {
        if ($('#FilesList tr').length > 1) {
            $("#FilesList").css("visibility", "visible");
        } else {
            $("#FilesList").css("visibility", "hidden");
        }
    }
    function DeleteServerFile(attachmentid) {
        $.ajax({
            url: '/Vendor/RemoveFiles',
            type: "POST",
            data: { Id: attachmentid },
            async: false,
            success: function (result) {
                if (result != "") {
                    //alert(result);
                    $("#" + attachmentid).remove();
                    chkatchtbl();
                }
            },
            error: function (err) {
                alert(err.statusText);
            }
        });
       
     }
</script>  